sudo: required

language: node_js

node_js:
  - node

services:
  - docker

before_install:
  - docker run -dit --name emscripten -v $(pwd):/src trzeci/emscripten:sdk-tag-1.37.33-64bit bash

before_script:
  - python -m SimpleHTTPServer &

script:
  - docker exec -it emscripten make
  - node test-browser/runner --file full.html --browser chrome --browser safari --browser firefox
  - node test-browser/runner --file lite.html --browser chrome --browser safari --browser firefox
  - node test-browser/runner --file fabric.html --browser chrome --browser safari --browser firefox --browser MicrosoftEdge --browser "internet explorer"

addons:
  sauce_connect: true

deploy:
  provider: releases
  api_key:
    secure: TvomQbnJJW1vCCD9GQLI0ulvuEkby78WgIM/O3jf4B8B6CdeZECjD/Nr1DmR/8j3oE5psEwnggdIxoD2L24tJ09jTTr+8cZCKX+o1M2ywJYUYBQHtm2v69b73bw7/sEHjOR+H8qLWtpJ7nQccP2MgWFdEkmGe/5r8Ilaqprwgqw=
  file:
    - viz.js
    - viz-lite.js
  on:
    tags: true
